spark.sql("""select mdm_affil_id ,to_mdm_party_id ,from_mdm_party_id ,affil_type,affil_st_dt,affil_end_dt,affil_attrib_03,mdm_last_mod_dt,mdm_ins_dt,affil_status_cd,affil_attrib_09,affil_attrib_08,affil_attrib_07 ,affil_attrib_06 ,affil_attrib_05 ,affil_attrib_04 ,affil_attrib_03 ,affil_attrib_02 ,affil_attrib_01,affil_hier from all_all_r_gbl_mdm.lnd_cdw_party_affil where mdm_affil_id is not null
minus
select stg.affiliationid,stg.parentid,stg.childid,stg.affiliationtype,stg.start_date,stg.end_date,stg.role,stg.mdm_last_mod_date,stg.mdm_ins_date,stg.affil_status_code,stg.affil_attrib_09,stg.affil_attrib_08,stg.affil_attrib_07,stg.affil_attrib_06,stg.affil_attrib_05,stg.affil_attrib_04,stg.affil_attrib_03,stg.affil_attrib_02,stg.affil_attrib_01,stg.affil_hier  from all_all_e_gbl_customer.idl_mdm_affln stg """).createOrReplaceTempView("idl_mdm_affln")

//below query using fetch insert and update records 

spark.sql("select distinct xref.* from all_all_r_gbl_mdm.lnd_cdw_party_affil xref left anti join idl_mdm_affln idl on trim(xref.mdm_affil_id)=trim(idl.mdm_affil_id) and xref.mdm_affil_id is not null union all select distinct xref.* from all_all_r_gbl_mdm.lnd_cdw_party_affil xref join idl_mdm_affln idl on trim(xref.mdm_affil_id)=trim(idl.mdm_affil_id)").createOrReplaceTempView("lnd_cdw_party_affil")


spark.sql("""insert into ALL_ALL_R_GBL_MDM.stg_mdm_affln select affiliation_id ,parent_id ,child_id ,affiliation_type ,start_date ,end_date ,primary ,nanobrick ,role ,mdm_last_mod_date ,mdm_ins_date ,affil_status_code ,affil_attrib_09 ,affil_attrib_08 ,affil_attrib_07 ,affil_attrib_06 ,affil_attrib_05 ,affil_attrib_04 ,affil_attrib_03 ,affil_attrib_02 ,affil_attrib_01 ,affil_hier ,rec_insert_date ,batch_id ,rec_insert_by ,reject_reason ,status_flag from (select mdm_affil_id affiliation_id, to_mdm_party_id parent_id, from_mdm_party_id child_id, affil_hier affil_hier, affil_type affiliation_type, affil_attrib_01 affil_attrib_01, affil_attrib_02 affil_attrib_02, affil_attrib_03 affil_attrib_03, affil_attrib_04 affil_attrib_04, affil_attrib_05 affil_attrib_05, affil_attrib_06 affil_attrib_06, affil_attrib_07 affil_attrib_07, affil_attrib_08 affil_attrib_08, affil_attrib_09 affil_attrib_09, affil_status_cd affil_status_code, affil_st_dt start_date, affil_end_dt end_date, mdm_ins_dt mdm_ins_date, mdm_last_mod_dt mdm_last_mod_date, 'FALSE' primary, null nanobrick, affil_attrib_03 role, current_timestamp() rec_insert_date, batch_id batch_id, 'MDM' rec_insert_by, null reject_reason, 'Y' status_flag from  lnd_cdw_party_affil where mdm_affil_id is not null  union select mdm_affil_id affiliation_id, to_mdm_party_id parent_id, from_mdm_party_id child_id, affil_hier affil_hier, affil_type affiliation_type, affil_attrib_01 affil_attrib_01, affil_attrib_02 affil_attrib_02, affil_attrib_03 affil_attrib_03, affil_attrib_04 affil_attrib_04, affil_attrib_05 affil_attrib_05, affil_attrib_06 affil_attrib_06, affil_attrib_07 affil_attrib_07, affil_attrib_08 affil_attrib_08, affil_attrib_09 affil_attrib_09, affil_status_cd affil_status_code, affil_st_dt start_date, affil_end_dt end_date, mdm_ins_dt mdm_ins_date, mdm_last_mod_dt mdm_last_mod_date, 'FALSE' primary, null nanobrick, affil_attrib_03 role, current_timestamp() rec_insert_date, batch_id batch_id, 'MDM' rec_insert_by, 'BAD RECORD: NO AFFILIATION ID' reject_reason, 'E' status_flag from  lnd_cdw_party_affil where mdm_affil_id is null )""")

